name: Training Gensim's Word2Vec on non-language data
description: Training Gensim's Word2Vec on non-language data
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-07-13"
api_version: 1